<a href="https://colab.research.google.com/github/shaina-12/Pytorch-Tuitorials/blob/main/Automatic_Differentiation_With_torch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
x = torch.zeros(5) # input tensor
x

tensor([0., 0., 0., 0., 0.])

In [4]:
y = torch.ones(3) # expected output
y

tensor([1., 1., 1.])

In [5]:
w = torch.randn(5,3,requires_grad=True)
w

tensor([[-0.6824,  0.3096,  0.4282],
        [ 0.2119,  0.4811,  0.9912],
        [-0.9632, -0.1322, -0.1373],
        [-1.2279, -0.3041,  0.5988],
        [-1.2063, -0.5569, -2.1807]], requires_grad=True)

In [6]:
b = torch.randn(3,requires_grad=True)
b

tensor([-0.7074, -1.0897,  2.1663], requires_grad=True)

In [7]:
z = torch.matmul(x,w)+b
z

tensor([-0.7074, -1.0897,  2.1663], grad_fn=<AddBackward0>)

In [8]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)
loss

tensor(0.8654, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [9]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7ff3152db990>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7ff3152dbd50>


In [10]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-0., -0., -0.],
        [-0., -0., -0.],
        [-0., -0., -0.],
        [-0., -0., -0.],
        [-0., -0., -0.]])
tensor([-0.2233, -0.2494, -0.0343])


In [11]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [12]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


In [13]:
inp = torch.eye(5, requires_grad=True)
out = (inp+1).pow(2)
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])


In [14]:
inp

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)

In [15]:
out

tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)